basePath: /
definitions:
  core.Event:
    properties:
      amount:
        type: number
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      type:
        type: string
    type: object
  core.Invite:
    properties:
      created_at:
        type: string
      id:
        type: string
      status:
        $ref: '#/definitions/core.InviteStatus'
      user:
        $ref: '#/definitions/core.User'
    type: object
  core.InviteStatus:
    enum:
    - pending
    - canceled
    - accepted
    - rejected
    type: string
    x-enum-varnames:
    - InviteStatusPending
    - InviteStatusCanceled
    - InviteStatusAccepted
    - InviteStatusRejected
  core.User:
    properties:
      balance:
        type: number
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  handlers.AuthResponse:
    properties:
      token:
        type: string
    type: object
  handlers.GenericErrorResponse:
    properties:
      message:
        type: string
    type: object
  handlers.GenericSuccessResponse:
    properties:
      message:
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      database:
        type: boolean
    type: object
  handlers.createEventRequest:
    properties:
      amount:
        type: number
    type: object
  handlers.createInviteRequest:
    properties:
      email:
        type: string
    type: object
  handlers.createUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handlers.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: not@stneto.dev
    name: API Support
    url: https://stneto.dev
  description: This is a generic app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Banking API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      summary: Authenticate user
      tags:
      - auth
  /auth/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: User profile
      tags:
      - auth
  /auth/register:
    post:
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.createUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      summary: Create user
      tags:
      - auth
  /events/deposit:
    post:
      parameters:
      - description: Event params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.createEventRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.GenericSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create deposit for the user
      tags:
      - event
  /events/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.Event'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List user events
      tags:
      - event
  /events/withdraw:
    post:
      parameters:
      - description: Event params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.createEventRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.GenericSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create withdraw for the user
      tags:
      - event
  /friends/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List user friends
      tags:
      - friend
  /friends/remove/{id}:
    post:
      parameters:
      - description: Friend ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Remove friend
      tags:
      - friend
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Show health status
      tags:
      - system
  /invites/accept/{id}:
    post:
      parameters:
      - description: Invite ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Accept an user received invite
      tags:
      - invite
  /invites/cancel/{id}:
    post:
      parameters:
      - description: Invite ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Cancel an user sent invite
      tags:
      - invite
  /invites/create:
    post:
      parameters:
      - description: Invite params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.createInviteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.GenericSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create invite to a user
      tags:
      - invite
  /invites/received:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.Invite'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List user received invites
      tags:
      - invite
  /invites/reject/{id}:
    post:
      parameters:
      - description: Invite ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Reject an user received invite
      tags:
      - invite
  /invites/sent:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.Invite'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List user sent invites
      tags:
      - invite
securityDefinitions:
  ApiKeyAuth:
    description: JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
