basePath: /
definitions:
  core.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  handlers.AuthResponse:
    properties:
      token:
        type: string
    type: object
  handlers.GenericErrorResponse:
    properties:
      message:
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      database:
        type: boolean
    type: object
  handlers.createUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handlers.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: not@stneto.dev
    name: API Support
    url: https://stneto.dev
  description: This is a generic app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Banking API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      summary: Authenticate user
      tags:
      - auth
  /auth/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: User profile
      tags:
      - auth
  /auth/register:
    post:
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.createUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericErrorResponse'
      summary: Create user
      tags:
      - auth
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Show health status
      tags:
      - system
securityDefinitions:
  ApiKeyAuth:
    description: JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
